parameters:
  mullenlowe.etl.foo.class: Mullenlowe\EtlBundle\Service\ClassA

services:
    _defaults: { autowire: true }

    mullenlowe.etl.foo:
      class: %mullenlowe.etl.foo.class%
      arguments: [ '%param1%', '%param2%' ]
